### ISSUE TITLE
VersionBot constantly reports broken tests, not only change

### ISSUE THREAD

**Issue by CameronDiver** [resin-io-modules/resin-procbots#168]
I had a pretty hard to find bug in https://github.com/resin-io/resin-builder/pull/202 which repeatedly failed (I push to test because ironically jenkins is a lot faster). That resulted in a lot of versionbot messages telling me that the tests failed.

While useful, I feel like these messages would be best if they only reported on state change.

I also know that VB is stateless, so this may not be possible, but it would be good.

**Comment by hedss** [comment]
It's actually designed to be explicit. The idea is if you commit non-working code then you're told about it immediately. If beforehand it didn't work, and then you commit code that is working, you wouldn't expect to get a message, instead reviewers can now look at it. However, if it wasn't working, and you commit more non-working code, then it'll let you know again so it's obvious. Is this more of a process failure? Maybe we need to expose a better way of testing before it gets into PR?

**Comment by CameronDiver** [comment]
Yeah I agree with the testing part, but in this particular instance, it was already in PR, then a change was suggested which subtly broke everything. 

I see what you're getting at, but it's almost like saying there's no need to have CI because the tests should be ran locally.

**Comment by hedss** [comment]
I'm definitely not saying the latter! :) But the point is more that the CI testing is there to make sure it's doing what it should at the end of development. I'm not convinced we should change this, because the ideal state is that any new commit fixes things, rather than continues them as broken.

@lekkas @flesler What are your opinions on this? (I'm interested in Ariel's opinion as his suggestion is what sparked this feature.)

**Comment by flesler** [comment]
>I push to test because ironically jenkins is a lot faster
I think here's the problem.

I think the feature is spot on, we were getting emails for anything that changes on a PR (comments, reviews, commits, etc.) except for failed tests. This would make it likely that one forgets about the PR if one switched to something else while waiting.

I don't want to generalize too much, but I'd say that at least for most cases, we shouldn't be using the CI server to test and even more so, we shouldn't create a PR for code that is not ready for review.

**Comment by CameronDiver** [comment]
> we shouldn't create a PR for code that is not ready for review

but in this case, it was a changing requirement *after* the PR was opened. Are we saying that a PR should be closed in that case?

I'm also not sure I agree we shouldn't be using CI to test, we have the infrastructure there for that exact role, why not utilise?

**Comment by flesler** [comment]
I don't say that, we could try to find a better solution but maybe we won't find it. What I'm saying is, if you end up in this situation and decide to test on the CI, you'll get a lot of emails and maybe that's ok because, at the moment, you are the exception and not the rule and getting those emails is pretty harmless.

About using the CI, I think usually we should run it locally first, I think the CI is a backup check. On the VPN we added the tests to the `prepush`, I think it's a good idea. Obviously the builder tests take a whole lot more so again, could be the exception and we could try to find a way to make it better for devs working on the builder

**Comment by CameronDiver** [comment]
I agree that this highlights an issue in the tests on the builder, that they take too long, and should be fixed. Ignoring that for a second though, and using CircleCI as a case-study, you get an email to say either "Your build has broken", or "Your tests are now passing". 
I believe the state change is much more effective at actually informing the user what is going on.

**Comment by hedss** [comment]
There's another way to tackle this, which is to simply add the `procbots/versionbot/no-checks` label. At this point, VB gives up on the PR and doesn't bother to check it. Saying that, I've an outstanding to look at this as it appears to not be working. However, ideally, this would solve the problem wouldn't it?

**Comment by CameronDiver** [comment]
Ah @hedss that's a much better method! Yeah I'm fully in agreement, once that label works it makes this issue completely irrelevant :)

**Comment by flesler** [comment]
@CameronDiver by the state you mean in the GH UI for the PR? You need to be "polling" that tab to see if it worked rather than getting notified. Also in most cases tests should pass so it's a better default (IMO) to push-and-forget and get notified if the exception (tests fail) happened than polling that tab

**Comment by lekkas** [comment]
I agree that in this case (painfully slow local development as @CameronDiver noted) it's fair to treat the remote PR branch as a development one, for the sake of saving dev time and that means that state changes would be more appropriate. 

While I don't feel strongly about it, I agree that state change comments/notifications might be more appropriate in general (and to reframe this a bit, why not also get 'success' messages from VersionBot for each pushed commit that passes tests?)

That said, for components that have reasonable test running times [we want to introduce `prepush` hooks everywhere](https://github.com/resin-io/process/blob/master/process/maintaining-a-project.md#general-housekeeping) as @flesler noted so in practice failed test message spamming won't be an issue. And for exception like the builder, the `procbots/versionbot/no-checks` label looks like the best way forward

**Comment by CameronDiver** [comment]
@flesler State change being "failing" -> "passed" or "passed" -> "failing", not "passed" -> "passed" or "failing" -> "failing".

@lekkas fully agreed that the best way forward for this is to use the label. To that end I'm going to close this issue - @anybody feel free to re-open if you feel we haven't gotten to the bottom of the issue at hand.

**Comment by hedss** [comment]
In response to the argument that we don't get a success message every time, that's because it's the desired outcome of a push to a PR. This means an author is free to go on their way and now it's down to reviewers. On the other hand, if a failure occurs, they need to know ASAP so they can do something about it before reviewers step in (nobody's going to review failing code).

The point of adding the failed status was that it only pings you if you need to know. If you're pinged on state change (yes, now it works) then essentially you're being brought back into a PR that, actually, you just want to ignore until it's reviewed.

I can see both sides of the argument, tbh, but in normal circumstances I still agree with Ariel that PRs are normally 'now it's ready to be merged' rather than 'here's a quick way of building something to test'. Hence suggestion of the `no-checks` label.

**Comment by lurch** [comment]
> I can see both sides of the argument

Well, what about if VersionBot continued to follow the current behaviour, but could also respond differently if a `procbots/versionbot/statechange-checks` label was added (in which case it'd report only when the status changes from failing->passing or passing->failing, as @CameronDiver was requesting) ?

I'll let @CameronDiver add that as a feature-request if he thinks it's a good idea ;-)

**Comment by hedss** [comment]
I reaaaaally don't like that, because that now means the flow of a PR changes depending on a label added to a particular PR. This now makes authors and reviewers (and commenters) not actually know what's going on, and why in one PR something gets reported an in another it doesn't.

**Comment by CameronDiver** [comment]
Yeah I think for me what this boils down to is not that I want it done "my" way, but just have a way of doing it. It's OK to say that things *should* be done (e.g. tests should always pass when a PR is up), but that is not always the case and as long as we have a method of combating it in those cases then I'm happy :)

**Comment by lurch** [comment]
Oh, I saw it as a 'complement' to `procbots/versionbot/no-checks`, but fair enough, I'm obviously not as deeply involved in the 'process' process :)

**Comment by flesler** [comment]
> is not that I want it done "my" way, but just have a way of achieving the same outcome. 
@CameronDiver that was nicely said, keep the poetry coming dude
