### ISSUE TITLE
VersionBot: `procbots/versionbot/no-checks` label gets blocked by AutoMerge

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#227]
Whilst using the `no-checks` label now works, it still gets blocked because the other VB requirements need a working status change to allow a merge.

So, we need to see the label and set Versionist/Reviews/etc. checks to pass and allow a manual merge to go ahead (adding the `ready-to-merge` label will simply not be honoured as the `no-checks` label suppresses it).

**Comment by lurch** [comment]
So, AFAICT this feature is desired so that a 'tiny' PR (e.g. https://github.com/resin-io/resin-git/pull/54 ) can be merged without causing versionist to do a 'noisy' full version bump. IMHO rather than changing the semantics around the `no-checks` and `ready-to-merge` labels, I still think the `Change-Type: none` is a better solution to this situation. It feels to me like a more "generic" solution, as it only turns off the version-bumping, and doesn't turn off the other checks e.g. reviewers and required-footer-tags. (but of course there may well be other aspects to this that I'm missing!)

**Comment by hedss** [comment]
@lurch There's been several meetings about this this week, and because of other factors and long-term plans, the consensus is to leave as is currently.
Latest arch call: https://drive.google.com/open?id=0B0NS-URBofBLbGQwRlBJZFBJdE0

**Comment by hedss** [comment]
@lurch I think to be clearer, my original comment here is confusing. What I'm saying is that in the `no-check` case:

* `Versionist` status is automatically passed
* `AutoMerge` status is automatcally passed (to allow manual merging)
* Reviewer checks would still occur, though, because these are *not* related to versionbumping or the merging of VersionBot

Should have been clearer with what I meant by 'set Versionist/Reviews/etc. checks to pass'.
