### ISSUE TITLE
SyncBot, ProcBots: Could contain a command (line) infrastructure

### ISSUE THREAD

**Issue by sqweelygig** [resin-io-modules/resin-procbots#390]
SyncBot, and possibly the ProcBots framework, could support a set of commands that pertain to the process itself.  Things like `info` and `kill`, protected by a secret in the env vars.

**Comment by lurch** [comment]
Would @hedss be able to `kick` VersionBot? :joy:

**Comment by hedss** [comment]
The way I envisage this working is the the ProcBot class includes a command parser method, which when receiving commands will, like Zhu Li, 'do the thing'.

This can then be hooked in *if required* by an inheriting child bot by calling the method as part of an event registration.

For example, imagine that we want to be able to use this in Github. We most definitely don't want general access on public repositories, as any reported information could potentially be used as a security breach. So maybe we ask VersionBot/SyncBot/WotBot to only honour the parser in private repositories. We can go further than this too, we can setup a whitelist so that only specific users are allowed to use the parser. And we can go even further than this, perhaps ensuring that only comments in a PR can trigger it.

Take then, the `checkFooterTags` in VersionBot, which receives an event.
```typescript
protected checkFooterTags = (_registration: GithubRegistration, event: ServiceEvent): Promise<void> => {
    ...
    return this.dispatchToEmitter(this.githubEmitterName, {
        data: {
        owner,
	repo: name,
	number: pr.number,
    },
    method: this.githubApi.issues.getComments
    }).then((comments: GithubApiTypes.Comment[]) => {
        _.each(comments, (comment) => {
            if ((comment.body === 'status') && 
                _.find(['hedss', 'sqweelygig', 'brownjohnf'], (user) => { comment.user === user })) {
                    this.parseCommand(comment.body);
            }
        });
    }).then(...
    );
}
```
We could have a configurable whitelist, etc. etc, but you get the idea.
