### ISSUE TITLE
VersionBot: Allow authors of a PR to also start merge should there be a set of maintainers

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-procbots#73]
The reasoning behind #72 came down to ensuring that the pipeline wasn't delayed if maintainers weren't able to get through PRs swiftly. This is compounded if there's a configuration file that only allows certain engineers (the maintainers of a repository) to start the merge.

The solution is to allow either authorised maintainers **or** the original author of the PR to apply the `procbots/versionbot/ready-to-merge` label.

Should be a quick fix.

**Comment by lurch** [comment]
Should this also be a feature that's configurable on a per-repo basis using `procbots.yml` ?

I guess this feature needs to be used with care on any public repos where Joe Bloggs can submit a PR to a resin.io repo - we obviously wouldn't want VersionBot automatically merging random PRs from the public just because the original author happened to add a `procbots/versionbot/ready-to-merge` label.

**Comment by lekkas** [comment]
@lurch that's a fair point. For private repos access control is performed by github essentially so it should be fine to act on a  `
procbots/versionbot/ready-to-merge` label set by the PR Author.

For public repos, setting the label will only have an effect if the user who adds it is listed in the `maintainers` property of `.procbots.yml`

Does this make sense?

**Comment by lekkas** [comment]
Connects to https://github.com/resin-io/hq/pull/730

**Comment by lurch** [comment]
...but then resin.io employees (who aren't listed as a maintainer in any repos) might get confused why they _can_ apply the `procbots/versionbot/ready-to-merge` label on a private repo, but _can't_ apply the label on a public repo? (when you're jumping between multiple repos, it's not immediately obvious which is which unless you remember to double check).

I hesitate to suggest it :confounded: but does VersionBot need to be able to lookup a user's organisation membership, so that it can tell which users are (current) resin.io employees? Or does that not give fine-grained enough details? \*shrug\*

**Comment by alexandrosm** [comment]
@lekkas confused. Are we going back on author being able to merge if
approved?

On Mar 30, 2017 5:01 AM, "Andrew Scheller" <notifications@github.com> wrote:

...but then resin.io employees (who aren't listed as a maintainer in any
repos) might get confused why they *can* apply the
procbots/versionbot/ready-to-merge label on a private repo, but *can't*
apply the label on a public repo? (when you're jumping between multiple
repos, it's not immediately obvious which is which unless you remember to
double check).

I hesitate to suggest it 😖 but does VersionBot need to be able to lookup a
user's organisation membership, so that it can tell which users are
(current) resin.io employees? Or does that not give fine-grained enough
details? *shrug*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/resin-io-modules/resin-procbots/issues/73#issuecomment-290279948>,
or mute the thread

**Comment by lekkas** [comment]
@alexandros yes, a PR author will be able to merge if approved. 

We still have to limit this to resin.io members tho,  so we can either check the author's org (as @lurch suggested), or be more restrictive by listing specific, whitelisted authors in procbots.yml (which is why I mentioned using the 'maintainers' property to do this, ma We can even use a combination

**Comment by alexandrosm** [comment]
yeah, perhaps we can have a global whitelisted "resineers" list? cc @hedss?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by hedss** [comment]
I think we don't need any sort of extra authors list (or add people as maintainers) as long as https://github.com/resin-io-modules/resin-procbots/issues/27 and https://github.com/resin-io-modules/resin-procbots/issues/31 are satisfied.

That is, we can add authorised reviewers to the `.procbots.yml` configuration file for a repository and ensure that only reviewers who are authorised can approve a PR. We'd have an extra status for repos that require authorised maintainers, `ApprovedReviewer` or the like.

This means that whilst anyone can author a PR (and in fact there'd be nothing stopping that anyway), nobody can actually merge it unless an authorised reviewer had given the go ahead. This stops having to have extra checks/lists that exist only for authors.

Sound ok?

**Comment by lurch** [comment]
So what would then be the difference (in terms of ProcBots) between a "maintainer" and an "authorised reviewer" ?

**Comment by hedss** [comment]
Maintainer can merge the PR into the repo as they're responsible for the component. A reviewer is given authority to review. If you look at a lot of services as we have them at the moment, we have 'trusted' people that are used for reviews, but ultimately won't merge those PRs into the repository.

**Comment by lurch** [comment]
Ahhh, I think I'm getting muddled up between the "merging the PR", "applying the `procbots/versionbot/ready-to-merge` label", "approving the PR" & "adding a review" terms, and "author / maintainer / authorised maintainers / reviewer / authorised reviewer / approved reviewer" roles  ;-)
(which would probably all be clarified if actually took the time to read the relevant HQ specs)

**Comment by hedss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 1](https://trello.com/c/EhnN4LpX/1-issue-1)

**Comment by hedss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VersionBot: Allow author of a PR to also start merge should there be a set of maintainers](https://trello.com/c/aM1d24HU/4-versionbot-allow-author-of-a-pr-to-also-start-merge-should-there-be-a-set-of-maintainers)

**Comment by hedss** [comment]
Important caveat: For this to work, a maintainer **must** be one of the reviewers who have approved the review.

**Comment by lekkas** [comment]
@hedss following up on with what we discussed in the process call, do we need separate `approved_reviewers` and `minimum_approvals` configuration options? Won't the `maintainers` list be sufficient? In any case, shouldn't maintainers automatically be considered authorised reviewers? I mean, even if we keep the `authorised_reviewers' it'd be nice if we didn't have to maintain/duplicate the maintainer's handles in both places

**Comment by hedss** [comment]
Well, I think you're right in a way that the maintainers list should also imply they're approved reviewers. However, @alexandrosm mentioned a number of minimum approvals before, which implies to me that as long as one of the reviewers is a maintainer, then the PR can be merged.

Consider a PR raised, where:
```
minimum_approvals: 2
approved_reviewers:
    - Bob
    - Josephine
maintainers:
   - Helen
   - George
```
An author can merge the PR as long as two people have approved, but one of them is a maintainer, eg. approvals from Bob and Helen allow a PR merge, but approvals from Bob and Josephine don't.

Does that make sense? It means that if we want to be ultra cautious on a component, we don't need every maintainer to look at it as long as there are other trusted reviewers. If not, I'm happy just to stick with the maintainers list.

**Comment by lurch** [comment]
> the maintainers list should also imply they're approved reviewers.

@hedss When I asked you about that previously on another issue, you said that the lists should be explicitly distinct ;-)  (something about "professional distance" IIRC)

I'm reluctant to suggest more complexity, but OTOH allowing more configurable options will allow each project using VersionBot to adapt it to their particular needs...
You _could_ also add extra `minimum_maintainer_approvals` (defaulting to `0` if absent) and `maintainers_can_approve` (defaulting to `false` if absent) options, and then you could have configurations like:

---

```
minimum_approvals: 1
approved_reviewers:
    - Bob
    - Josephine
maintainers:
    - Helen
    - George
```
(either Bob and Josephine need to approve, approvals from Helen or George don't count towards the `minimum_approvals` total)

---

```
minimum_approvals: 2
approved_reviewers:
    - Bob
    - Josephine
maintainers:
    - Helen
    - George
```
(both Bob and Josephine need to approve, approvals from Helen or George don't count towards the `minimum_approvals` total)

---

```
minimum_approvals: 2
approved_reviewers:
    - Bob
    - Josephine
    - Helen
maintainers:
    - Helen
    - George
```
(require two approvals from any of Bob, Josephine or Helen, approvals from George don't count towards the `minimum_approvals` total)

---

```
minimum_approvals: 2
maintainers_can_approve: true
approved_reviewers:
    - Bob
    - Josephine
maintainers:
    - Helen
    - George
```
(require 2 approvals from any of Bob, Josephine, Helen or George. Setting `maintainers_can_approve` to true implicitly appends the `maintainers` list to the `approved_reviewers` list)

---

```
minimum_approvals: 2
minimum_maintainer_approvals: 1
approved_reviewers:
    - Bob
    - Josephine
maintainers:
    - Helen
    - George
```
(require 2 approvals from any of Bob, Josephine, Helen or George, with at least one of them being from Helen or George. Setting `minimum_maintainer_approvals` > 0 implicitly sets `maintainers_can_approve` to true)

---

```
minimum_approvals: 1
minimum_maintainer_approvals: 2
approved_reviewers:
    - Bob
    - Josephine
maintainers:
    - Helen
    - George
```
(require approvals from both Helen and George. Setting `minimum_maintainer_approvals` >= `minimum_approvals` overrides the `minimum_approvals` setting and effectively makes the `approved_reviewers` list defunct)

---

```
minimum_approvals: 3
minimum_maintainer_approvals: 2
approved_reviewers:
    - Bob
    - Josephine
maintainers:
    - Helen
    - George
```
(require approvals from both Helen and George, **and** an approval from either Bob or Josephine)

---

I _think_ that encompasses every combination I can come up with, and hopefully doesn't add _too_ much extra complexity.
Just a suggestion, of course :-)

**Comment by hedss** [comment]
@lurch Goalposts move, as do requirements. We've been discussing this internally, and it's been decided that authors can merge PRs as long as at least one maintainer has authorised it.

Internally, at Resin, this seems unlikely to change given it'll be part of the process. I don't think adding `minumum_maintainer_approvals` will alter that, esp. as multi-maintainers aren't very common.

Hence the suggestion to just ensure there are the minimum number of reviews and at least one is from a maintainer. Frankly, I've a lot of issues to go through and I really don't want to make this more complex than required.

**Comment by lurch** [comment]
An idea I've just had...  (I'm gonna use a bit of a contrived example to illustrate my point)

If repoX has:
```
minimum_approvals: 2
approved_reviewers:
    - Bob
    - Josephine
maintainers:
    - Helen
    - George
```

and repoY has:
```
minimum_approvals: 1
approved_reviewers:
    - Bob
    - Sandra
maintainers:
    - George
```

and repoZ has:
```
minimum_approvals: 3
approved_reviewers:
    - Josephine
    - Fred
    - Bob
    - Simon
    - Harriet
maintainers:
    - Sandra
    - George
```

Given that Bob is going to be reviewing PRs on repoX, repoY and repoZ, maybe it'd be useful for there to be a comment on each PR, or some other mechanism in place, so that Bob knows for each PR he looks at, how many minimum approvals it needs? E.g. if a PR on repoX already has two approved reviews, then Bob knows he doesn't need to add his review, but if a PR on repoZ already has two approved reviews, then Bob knows that it needs at least one more approved review before it can be merged.

Feel free to ignore if this is an unlikely situation :)

**Comment by hedss** [comment]
That's a really good idea, dude! I like the idea of adding a comment on initial PR saying what the review conditions are! @lekkas Thoughts?

**Comment by alexandrosm** [comment]
And maybe then we could also have versionbot produce a "your reviews needed
here" view somewhere or other?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by lekkas** [comment]
@lurch I think we are overcomplicating by introducing the`minimum_maintainer_approvals` and `maintainers_can_approve` options, because these imply that a maintainer's reviews can simply be ignored, which makes no sense in our resin.io workflow. Ι'd rather we go with the simple approach first and only consider extra options if a requirement comes up, instead of preemptively trying to solve problems that are not relevant to our workflow. I'm open to revisiting this of course after we give it a first run.

For that reason, I suggest we keep it simple and support these options in the first iteration

```
minimum_approvals: 1
reviewers:
    - Bob
    - Sandra
maintainers:
    - George
```

- `minimum_approvals` must be >=1 and defaults to 1
- maintainers' approvals always count for the minimum_approvals setting
- At least one approval must originate from a maintainer.
- Note: by approve/approval I mean giving an approval by using the github review feature

I like the idea of having a notification on reviews required, but instead of a comment, how hard would it be to present this in the PR status, like we do for `versionbot` change-type checks? Ideally it would be updated after every approval, e.g. `0/2 approvals given`, `1/2 approvals given` etc.

**Comment by lurch** [comment]
> And maybe then we could also have versionbot produce a "your reviews needed here" view somewhere or other?

Nice idea. If something like that gets added, it might also be useful to have a "you **must** review these" and "you _should_ / _could_ review these" distinctions.
If we had the example of:
```yaml
minimum_approvals: 1
reviewers:
    - Bob
    - Sandra
maintainers:
    - George
```
then as there's only a single maintainer, George would be told that he **must** review each PR.

With an example of:
```yaml
minimum_approvals: 2
reviewers:
    - Bob
    - Sandra
maintainers:
    - George
```
then George would be told he **must** review, and Bob and Sandra would be told they _should_ review.

With an example of:
```yaml
minimum_approvals: 2
reviewers:
    - Bob
    - Sandra
maintainers:
    - Josephine
    - George
```
then Josephine, George, Bob and Sandra will all be told they _should_ review.

And finally with an example of:
```yaml
minimum_approvals: 2
reviewers:
    - Sandra
maintainers:
    - George
```
then both George and Sandra **must** review.
And of course once a PR has met it's minimum number of approvals, and had at least one maintainer approval, it should automatically disappear from everyone's "should review" lists.

**Comment by hedss** [comment]
@lekkas Yes to all of the above:
> * Lower prio I guess, but it'd be nice to have all handles listed in maintainers and reviewers automatically added as reviewers in all PRs of a given repo

Very doable.

> I like the idea of having a notification on reviews required, but instead of a comment, how hard would it be to present this in the PR status, like we do for versionbot change-type checks? Ideally it would be updated after every approval, e.g. 0/2 approvals given, 1/2 approvals given etc.

Just another status check. Each time a review is approved, check number of reviews. If reviews > minimum reviews (and at least one of maintainers is one of the reviewers) then status check passes, else it fails. We have control over the message, so can easily put in the 'x/y approvals met' message.

**Comment by lekkas** [comment]
> Of course, if they do assign reviewers, it'll assign any not already assigned that are in the config.

That would be awesome imo :)

> We have control over the message, so can easily put in the 'x/y approvals met' message.

I vote for this option, so that we can keep the comment section briefer, report status updates in the PR status view that is already there and have a `# of approvals` status check turn into a satisfying green when n/n approvals have been given
